version: "3"

services:
  caddy:
    image: caddy
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy:/etc/caddy
      - ./website:/data/webroot

  mirror-dockerhub:
    image: registry:2
    container_name: mirror-dockerhub
    command: "/etc/docker/registry/dockerhub.yml"
    volumes:
      - ./registry:/etc/docker/registry
      - ./caches/docker-registry/dockerhub:/var/lib/registry

  mirror-gcr:
    image: registry:2
    container_name: mirror-gcr
    command: "/etc/docker/registry/gcr.yml"
    volumes:
      - ./registry:/etc/docker/registry
      - ./caches/docker-registry/gcr:/var/lib/registry

  goproxy:
    image: goproxy/goproxy:latest
    container_name: goproxy
    command: "-listen=0.0.0.0:5100 -cacheDir=/ext"
    ports:
      - "5100:5100"
    volumes:
      - ./caches/go-modules:/ext

  verdaccio:
    image: verdaccio/verdaccio
    container_name: npm-registry
    ports:
      - 4873:4873
    volumes:
      - ./caches/npm-registry:/verdaccio/storage

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
