version: "3"

services:
  caddy:
    image: caddy
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy:/etc/caddy
      - ./website:/data/webroot

  registry:
    image: registry:2
    container_name: docker-registry-mirror
    ports:
      - "5000:5000"
    volumes:
      - ./registry:/etc/docker/registry
      - ./caches/docker-registry:/var/lib/registry
  
  goproxy:
    image: goproxy/goproxy:latest
    container_name: goproxy
    command: "-listen=0.0.0.0:8081 -cacheDir=/ext"
    ports:
    - "8081:8081"
    volumes:
      - ./caches/go-modules:/ext

  verdaccio:
    image: verdaccio/verdaccio
    container_name: npm-registry
    ports:
      - 4873:4873
    volumes:
      - ./caches/npm-registry:/verdaccio/storage

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.0.0/24
