version: "3"

services:
  caddy:
    image: caddy
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy:/etc/caddy
      - ./website:/data/webroot

  registry:
    image: registry:2
    container_name: docker-registry-mirror
    ports:
      - "5000:5000"
    volumes:
      - ./registry:/etc/docker/registry
      - ./caches/docker-registry:/var/lib/registry

  docker-registry-proxy:
    image: rpardini/docker-registry-proxy:0.6.1 # Check and make sure this is the last released version
    container_name: docker-registry-proxy
    env_file: # This contains REGISTRIES and AUTH_REGISTRIES
      - ./secrets.env
    environment:
      - CACHE_MAX_SIZE=256g
      - ENABLE_MANIFEST_CACHE=true
    volumes:
      - ./docker_mirror_cache:/docker_mirror_cache # This will be up to CACHE_MAX_SIZE big
      - ./docker_mirror_certs:/ca
    ports:
      - 0.0.0.0:3128:3128 # 0.0.0.0 binds to all interfaces

  goproxy:
    image: goproxy/goproxy:latest
    container_name: goproxy
    command: "-listen=0.0.0.0:5100 -cacheDir=/ext"
    ports:
      - "5100:5100"
    volumes:
      - ./caches/go-modules:/ext

  verdaccio:
    image: verdaccio/verdaccio
    container_name: npm-registry
    ports:
      - 4873:4873
    volumes:
      - ./caches/npm-registry:/verdaccio/storage

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
